fragment QuotePriceFields on Price {
  currency
  amount
}

fragment QuoteWorkerProfileFields on Profile {
  name
  avatarUrl
}

fragment QuoteWorkerFields on User {
  id
  profile {
    ...QuoteWorkerProfileFields
  }
  worker {
    id
    isVerified
  }
}

fragment QuoteFields on Quote {
  id
  taskId
  workerUserId
  estimatedDuration
  price {
    ...QuotePriceFields
  }
  message
  status
  createdAt
  worker {
    ...QuoteWorkerFields
  }
}
