#import "../../../../../(dashboard)/earnings/graphql/orderFields.gql"
#import "./TaskLocationViewerFields.gql"
#import "./TaskPosterViewerFields.gql"
#import "./TaskTimelineFields.gql"

fragment TaskViewerFields on Task {
  id
  status
  location {
    ...TaskLocationViewerFields
  }
  poster {
    ...TaskPosterViewerFields
  }
  timeline {
    ...TaskTimelineEventFields
  }
  orders {
    ...OrderFields
    completionVerificationCode
  }
}
