query MyRequests($filter: TaskFilter, $sort: TaskSort) {
  me {
    tasksPosted(filter: $filter, sort: $sort) {
      id
      title
      description
      category
      budget {
        amount
        currency
        type
        paymentMethod
      }
      datetime {
        date
        time
        type
      }
      images
      status
      location {
        lat
        lng
        name
        address
      }
      poster {
        id
      }
      quotes {
        id
        taskId
        workerUserId
        price {
          currency
          amount
        }
        message
        status
        createdAt
        worker {
          id
          profile {
            name
            avatarUrl
          }
        }
      }
    }
  }
}
