query WorkersDirectory($filter: WorkerFilter, $sort: WorkerSort) {
  workers(filter: $filter, sort: $sort) {
    id
    tagline
    isVerified
    yearsExperience
    tasksCompletedCount
    location {
      name
    }
    user {
      profile {
        name
        avatarUrl
      }
    }
    profile {
      avatarUrl
    }
  }
}
