#import "./orderFields.gql"

query MyOrders($filter: MyOrdersFilter) {
  me {
    orders(filter: $filter) {
      ...OrderFields
    }
    worker {
      earnings {
        pending {
          amount
          currency
        }
      }
    }
  }
}
