mutation Register(
  $email: String!
  $password: String!
  $name: String
  $contactNumber: String
) {
  register(
    email: $email
    password: $password
    name: $name
    contactNumber: $contactNumber
  ) {
    token
    user {
      id
      email
      emailVerified
    }
  }
}
