mutation CreateWorkerSubscriptionCheckout(
  $successUrl: String!
  $cancelUrl: String!
) {
  createWorkerSubscriptionCheckout(
    successUrl: $successUrl
    cancelUrl: $cancelUrl
  ) {
    url
  }
}
