mutation UpdatePhoneNumber($contactNumber: String!) {
  updatePhoneNumber(contactNumber: $contactNumber) {
    id
    profile {
      contactNumber
      phoneVerified
    }
    workerEligibility
  }
}
