query MeWorkerSetup {
  me {
    id
    email
    emailVerified
    phoneVerified
    workerEligibility
    profile {
      name
      contactNumber
      avatarUrl
      dateOfBirth
      emailVerified
      phoneVerified
    }
    worker {
      id
      legalName
      bio
      tagline
      primaryCategory
      yearsExperience
      skills
      qualifications
      travelRadiusMiles
      portfolioUrls
      location {
        address
        lat
        lng
        name
      }
      setupProgress {
        currentSubStep
        completedSubSteps
        isComplete
      }
    }
  }
}
