#import "../../../../(dashboard)/earnings/graphql/orderFields.gql"

mutation AcceptQuote($quoteId: ID, $input: AcceptQuoteInput) {
  acceptQuote(quoteId: $quoteId, input: $input) {
    task {
      id
      status
    }
    order {
      ...OrderFields
    }
  }
}
