query Tasks($filter: TaskFilter, $sort: TaskSort) {
  tasks(filter: $filter, sort: $sort) {
    id
    title
    description
    category
    budget {
      amount
      currency
      type
      paymentMethod
    }
    datetime {
      date
      time
      type
    }
    images
    status
    views
    location {
      lat
      lng
      name
      address
    }
    poster {
      id
      profile {
        name
        avatarUrl
      }
    }
  }
}
