mutation ConfirmPhoneVerification($code: String!) {
  confirmPhoneVerification(code: $code) {
    id
    profile {
      contactNumber
      phoneVerified
    }
    workerEligibility {
      isEligible
      missing
    }
  }
}
