mutation ConfirmEmailVerification($token: String!) {
  confirmEmailVerification(token: $token) {
    id
    profile {
      emailVerified
    }
    workerEligibility {
      isEligible
      missing
    }
  }
}
