#import "./WorkerMembershipFields.gql"

query Me {
  me {
    id
    email
    emailVerified
    phoneVerified
    phoneVerifiedAt
    createdAt
    enabledLoginMethods
    profile {
      name
      contactNumber
      avatarUrl
      bio
      dateOfBirth
      defaultPreferredContactMethod
      emailVerified
      phoneVerified
    }
    settings {
      isProfilePrivate
      language
      marketingEmails
    }
    workerEligibility
    worker {
      id
      legalName
      bio
      tagline
      primaryCategory
      yearsExperience
      skills
      qualifications
      travelRadiusMiles
      portfolioUrls
      isVerified
      tasksCompletedCount
      locationAddress
      locationLat
      locationLng
      location {
        address
        lat
        lng
        name
      }
      setupProgress {
        currentSubStep
        completedSubSteps
        isComplete
      }
      membership {
        ...WorkerMembershipFields
      }
      earnings {
        pending {
          amount
          currency
        }
      }
    }
  }
}
