#import "./WorkerMembershipFields.gql"

fragment MeShell on User {
  id
  email
  disabled
  profile {
    name
    avatarUrl
  }
  worker {
    id
    membership {
      ...WorkerMembershipFields
    }
    earnings {
      pending {
        amount
        currency
      }
    }
  }
}
