query MyRequests($filter: TaskFilter) {
  myRequests(filter: $filter) {
    id
    title
    description
    category
    acceptedWorkerCap
    budget {
      amount
      currency
      type
      paymentMethod
    }
    datetime {
      date
      time
      type
    }
    contactMethod
    images
    status
    completedAt
    confirmedAt
    createdAt
    location {
      lat
      lng
      name
      address
    }
    poster {
      id
    }
    quotes {
      id
      taskId
      workerUserId
      price {
        currency
        amount
      }
      message
      status
      createdAt
      worker {
        id
        profile {
          name
          avatarUrl
        }
      }
    }
  }
}
